# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a473789d00359ddeb05502b17bec5ffb58685ddd7701f80391f6e76129b5e1cc9cf67086827bae1e85c9d289a9778aa2fd19d9f1e1ed6623d433a25301c68535

test:
  secret_key_base: 8ebbfda019b104b8a2c935aeb6a9f680667e9855bdfdcf093f6db058b3a9faa04314bddceeeccd3ebb4163f34bb4aa872a9376f56b9a691ebc04d7368bd642b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
